# Generated by Django 5.2.6 on 2025-10-02 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respondents', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvitation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlist',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('organization', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyinvitation',
            unique_together={('survey', 'contact')},
        ),
    ]
