# Generated by Django 5.2.7 on 2025-10-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0003_emailcampaign_invitationtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
