# Generated by Django 5.2.6 on 2025-10-02 02:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_email_verification_token_user_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkboxes'), ('dropdown', 'Dropdown'), ('rating', 'Rating Scale'), ('yes_no', 'Yes/No'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rating_min', models.IntegerField(blank=True, default=1, null=True)),
                ('rating_max', models.IntegerField(blank=True, default=5, null=True)),
                ('rating_min_label', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_max_label', models.CharField(blank=True, max_length=50, null=True)),
                ('placeholder_text', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('show_if_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_if_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('option_value', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'db_table': 'question_options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('collect_email', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='users.organization')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('completion_time_seconds', models.IntegerField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'db_table': 'responses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='SurveyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_responses', models.IntegerField(default=0)),
                ('completed_responses', models.IntegerField(default=0)),
                ('average_completion_time', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Survey Analytics',
                'verbose_name_plural': 'Survey Analytics',
                'db_table': 'survey_analytics',
            },
        ),
        migrations.CreateModel(
            name='SurveyTheme',
            fields=[
                ('theme_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('font_size', models.CharField(default='16px', max_length=20)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('show_progress_bar', models.BooleanField(default=True)),
                ('show_question_numbers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Survey Theme',
                'verbose_name_plural': 'Survey Themes',
                'db_table': 'survey_themes',
            },
        ),
        migrations.CreateModel(
            name='ResponseAnswer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response')),
                ('selected_options', models.ManyToManyField(blank=True, to='surveys.questionoption')),
            ],
            options={
                'verbose_name': 'Response Answer',
                'verbose_name_plural': 'Response Answers',
                'db_table': 'response_answers',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
