# Generated by Django 5.2.7 on 2025-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_apikey_apiusagelog_webhook_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_usage_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='trialing', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='surveys_created_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=50),
        ),
    ]
